{"name": "Verify a successful user retrieval", "status": "failed", "statusDetails": {"message": "AssertionError: Expected message 'Successful' not found in response\n", "trace": "  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"steps/sample_steps.py\", line 22, in step_then_response_message\n    assert expected_message in context.response.text, f\"Expected message '{expected_message}' not found in response\"\n"}, "start": 1701981634891, "stop": 1701981635350, "uuid": "f31810b2-ec4d-45e5-90e5-881e2238b3d6", "historyId": "81cc29b659dd70f51d7fa9a136df497d", "fullName": "API Tests on Reqres Public API: Verify a successful user retrieval", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "API Tests on Reqres Public API"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}